=== larsnaesbye/mars-sim2/mars-sim/mars-sim-core/src/main/resources/conf/dtd/crops.dtd
<!ELEMENT crop-list (crop*)>
<!ELEMENT crop EMPTY>
<!ATTLIST crop name CDATA #REQUIRED>
<!ATTLIST crop growing-time CDATA #REQUIRED>
<!ATTLIST crop crop-category CDATA #REQUIRED>
<!ATTLIST crop ppf CDATA #REQUIRED>
<!ATTLIST crop photoperiod CDATA #REQUIRED>
<!ATTLIST crop harvest-index CDATA #REQUIRED>

=== larsnaesbye/mars-sim2/mars-sim/mars-sim-core/src/main/resources/conf/crops.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE crop-list SYSTEM "conf/dtd/crops.dtd">

<crop-list>

<!-- References :
1. Crop Production for Advanced Life Support Systems, P.18 Table 6, 8-11-2006
2. NASA Advanced Life Support Baseline Values and Assumptions CR-2004-208941 http://ston.jsc.nasa.gov/collections/trs/_techrep/CR-2004-208941.pdf
3. Space Settlements: A Design Study 1975. http://settlement.arc.nasa.gov/75SummerStudy/5appendC.html
4. For Roots and tubers, see http://www.fao.org/es/faodef/fdef02e.htm
5. http://healthyeating.sfgate.com/list-fruits-vegetable-high-water-content-8958.html
 a. Vegetables that contain 92 percent water include
	cauliflower, eggplant, red cabbage, peppers and spinach.
 b. Broccoli is 91 percent water by weight.
 c. Additional healthy hydrating foods include carrots with 87 percent water and
	green peas and white potatoes with 79 percent water.
 d. water content:
	http://www2.ca.uky.edu/enri/pubs/enri129.pdf

6. Typical expected yield for food crop:
http://www.kzndae.gov.za/Portals/0/Horticulture/Veg%20prod/expected_yields.pdf

7. 01ICES-307 Design Parameters for Mars Deployable Greenhouses
http://www.marshome.org/files2/Bucklin1.pdf

growing-time : # of sols
crop-category : crop type
edible-biomass : in tonnes per hectare  or  gram / m^2 / day
edible-water-content : in proportion of 1 (1 is 100%)
inedible-biomass : in tonnes per hectare
daily-PAR : in mol /  m^2 / day

Note: 1 metric ton = 1 tonnes

8.  Photosynthetically active radiation (PAR), which is light with a wavelength
between 300/400 to 700 nm

Researchers measure instantaneous light in micromoles (μmol) per square
meter (m-2) per second (s-1), or: μmol·m-2·s-1 of PAR. This “quantum” unit quantifies the number of
photons (individual particles of energy) used in photosynthesis that fall on a square meter (10.8
square feet) every second.

This light measurement is an instantaneous reading.

Daily light integral (DLI) or Daily PAR is the amount of PAR received
each day as a function of light intensity (instantaneous light: μmol·m-2·s-1) and duration (day). It is expressed
as moles of light (mol) per square meter (m-2) per day (d-1), or: mol·m-2·d-1 (moles per day).
The DLI concept is like a rain gauge. Just as a rain gauge collects the total rain in a particular location over
a period of time, so DLI measures the total amount of PAR received in a day. Greenhouse growers can use
light meters to measure the number of light photons that accumulate in a square meter over a 24-hour period.

10.  Total water use and water requirement:
soybean: total: 845 kg, req :  414 kg per gram....

11. MPR Model: a crop model that consists of a set of nonlinear polynomial equations, six for each crop, developed using multivariate polynomial regression
(MPR).

The dependent variables for three of the six MPR equations are the relative growth rates
of (a) total dry mass prior to formation of yield bearing organs, (b) total dry mass after the
formation of yield bearing organs, and (c) yield dry mass.

The independent variables used in each equation include the average PPF, T, and CO2 values (averaged from planting date up to
the current time increment t), and the total or yield dry mass at t-1.

The model-based predictive controller adjusts light intensity, atmospheric/elevated atmospheric carbon dioxide concentration,
(photosynthetic photon flux (PPF), average daily air temperature (T),

http://www.usmarc.usda.gov/sp2UserFiles/ad_hoc/12755100FullTextPublicationspdf/Publications/fleisher/modelingcontrol2001.pdf
-->


	<crop name="Cabbage"
 	  	growing-time="85.0"
    	crop-category="Vegetables"
    	edible-biomass="75.78"
    	edible-water-content=".92"
    	inedible-biomass="6.74"
    	daily-PAR="17.28"
    	/>

	<crop name="Carrot"
    	growing-time="74.83"
    	crop-category="Roots"
    	edible-biomass="40"
    	edible-water-content=".88"
    	inedible-biomass="59.87"
    	daily-PAR="32.4"
    	/>

	<crop name="Swiss Chard"
    	growing-time="45.0"
    	crop-category="Vegetables"
    	edible-biomass="87.50"
    	edible-water-content=".92"
    	inedible-biomass="37.69"
    	daily-PAR="17.28"
    	/>

	<crop name="Celery"
    	growing-time="75.0"
    	crop-category="Vegetables"
    	edible-biomass="103.27"
    	edible-water-content=".90"
    	inedible-biomass="11.47"
    	daily-PAR="17.28"
    	/>

    <crop name="Kidney Bean"
    	growing-time="85.0"
    	crop-category="Legumes"
    	edible-biomass="11.11"
    	edible-water-content=".10"
    	inedible-biomass="150.0"
     	daily-PAR="25.92"
    	/>

    <crop name="Green Onion"
    	growing-time="50.0"
    	crop-category="Spices"
    	edible-biomass="81.82"
    	edible-water-content=".89"
    	inedible-biomass="10.0"
     	daily-PAR="17.28"
    	/>

    <crop name="Lettuce"
    	growing-time="28.0"
    	crop-category="Vegetables"
    	edible-biomass="35"
    	edible-water-content=".95"
    	inedible-biomass="5"
     	daily-PAR="17.28"
     	/>
    	<!-- http://www.fieldrobotics.org/~ssingh/VF/Challenges_in_Vertical_Farming/Schedule_files/GIACOMELLI.pdf
    	 10 kg / week yield for greenhouse  -->

    <crop name="White Onion"
    	growing-time="50.0"
    	crop-category="Bulbs"
    	edible-biomass="81.82"
    	edible-water-content=".89"
    	inedible-biomass="22.50"
     	daily-PAR="17.28"
    	/>

    <crop name="Peas"
        growing-time="75.0"
    	crop-category="Legumes"
    	edible-biomass="12.20"
    	edible-water-content=".79"
    	inedible-biomass="161.00"
     	daily-PAR="25.92"
    	/>


    <crop name="Peanut"
        growing-time="104.0"
    	crop-category="Legumes"
    	edible-biomass="6"
    	edible-water-content=".056"
    	inedible-biomass="18"
     	daily-PAR="32.4"
    	/>

     <crop name="Rice"
        growing-time="100.0"
    	crop-category="Grains"
    	edible-biomass="10.3"
    	edible-water-content=".12"
    	inedible-biomass="38"
     	daily-PAR="34.56"
    	/>

    <crop name="Wheat"
        growing-time="80"
    	crop-category="Grains"
    	edible-biomass="13"
    	edible-water-content=".12"
    	inedible-biomass="26"
     	daily-PAR="69.12"
    	/>

    <crop name="Potato"
    	growing-time="100.0"
    	crop-category="Tubers"
    	edible-biomass="35"
    	edible-water-content=".79"
    	inedible-biomass="15"
     	daily-PAR="34.56"
    	/>

     <crop name="Soybean"
        growing-time="93"
    	crop-category="Legumes"
    	edible-biomass="10"
    	edible-water-content=".10"
    	inedible-biomass="13"
    	daily-PAR="34.56"
    	/>

    <crop name="Garlic"
        growing-time="85"
    	crop-category="Bulbs"
    	edible-biomass="5.5"
    	edible-water-content=".58"
    	inedible-biomass="2.0"
    	daily-PAR="17.28"
    	/>
    	<!-- see http://nutritiondata.self.com/facts/vegetables-and-vegetable-products/2446/2 -->
    	<!-- http://www.dpi.nsw.gov.au/__data/assets/pdf_file/0018/470025/Garlic-gross-margin-budget.pdf
    	5494 kg/hectare or 549 g/sq meter or .5 kg/sqm or 5 kg/10sqm for 10 sqm space, -->

    <crop name="Sesame"
        growing-time="100"
    	crop-category="Flowers"
    	edible-biomass="7.2"
    	edible-water-content=".4"
    	inedible-biomass="15.0"
    	daily-PAR="17.28"
    	/>
    	<!--http://en.wiki2.org/wiki/Sesame
    	~50 to 80 seeds per capsule
    	7.2 Metric Ton/hectare -->

    <crop name="Tomato"
        growing-time="80"
    	crop-category="Fruits"
    	edible-biomass="17"
    	edible-water-content=".948"
    	inedible-biomass="20"
    	daily-PAR="32.4"
    	/>
    	<!-- http://www.ers.usda.gov/amber-waves/2005-april/north-american-greenhouse-tomatoes-emerge-as-a-major-market-force.aspx#.VHvwl1XF_ME
    	 484 MT/ha for earth greenhouse
    	 but 17.06 kg edible on Table 6 of Life support outputs of crops grown in BPC
    	  -->

   <crop name="Sugarcane"
        growing-time="180"
    	crop-category="Grasses"
    	edible-biomass="100"
    	edible-water-content=".75"
    	inedible-biomass="200"
    	daily-PAR="34.56"
    	/>
    	<!-- http://www.fao.org/docrep/005/x4988e/x4988e01.htm
    	http://www.fao.org/es/faodef/fdef03e.HTM
    	Both sugar beets and sugar cane have a high water content, accounting for about 75 percent of the total weight of the plants. The sugar content of sugar cane ranges from 10 to 15 percent of the total weight, while that of sugar beets is between 13 and 18 percent.
    	The protein and fat content of both beets and cane is almost nil.
    	100-300 Metric Ton/ha, ~10-15% sugar. After food processing, sugar is 40 kg (= 200 * 20%)
    	  -->


     <crop name="Ginger"
        growing-time="180"
    	crop-category="Roots"
    	edible-biomass="18"
    	edible-water-content=".12"
    	inedible-biomass="2"
    	daily-PAR="17.28"
    	/>
    	<!-- http://faostat.fao.org/site/339/default.aspx
    	http://agritech.tnau.ac.in/org_farm/orgfarm_ginger.html
    	http://www.tis-gdv.de/tis_e/ware/gewuerze/ingwerfr/ingwerfr.htm
   		1. Average yields in central Jamaica are 13-18 tonnes/ hectare
    	2. Harvesting is done from the 6th month onwards.
    	3.  TODO: making ginger Tea

    	 -->
    <crop name="Quinoa"
        growing-time="89"
    	crop-category="Grains"
    	edible-biomass="5"
    	edible-water-content=".1"
    	inedible-biomass="7"
    	daily-PAR="34.56"
    	/>
    	<!-- http://en.wiki2.org/wiki/Quinoa
    	http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19940015664.pdf
    	https://www.hort.purdue.edu/newcrop/proceedings1996/V3-632.html
    	1. The seed yield (often around 3 t/ha up to 5 t/ha) is comparable to wheat yields in the Andean areas.
    	2. The plants are allowed to stand until they are dry and the grain has reached a moisture content below 10%.
    	3. TODO:
    	 -->

   	<crop name="Strawberry"
        growing-time="45"
    	crop-category="Fruits"
    	edible-biomass="60"
    	edible-water-content=".92"
    	inedible-biomass="20"
    	daily-PAR="25.92"
    	/>
