=== larsnaesbye/mars-sim2/mars-sim/mars-sim-core/src/main/resources/conf/dtd/meals.dtd
<!ELEMENT meal-list (main-dish*, side-dish* )>
<!ELEMENT main-dish (ingredient+)>
<!ATTLIST main-dish id CDATA #REQUIRED>
<!ATTLIST main-dish name CDATA #REQUIRED>
<!ATTLIST main-dish oil CDATA #REQUIRED>
<!ATTLIST main-dish salt CDATA #REQUIRED>
<!ATTLIST main-dish category CDATA #REQUIRED>
<!ELEMENT side-dish (ingredient+)>
<!ATTLIST side-dish id CDATA #REQUIRED>
<!ATTLIST side-dish name CDATA #REQUIRED>
<!ATTLIST side-dish oil CDATA #REQUIRED>
<!ATTLIST side-dish salt CDATA #REQUIRED>
<!ATTLIST side-dish category CDATA #REQUIRED>
<!ELEMENT ingredient EMPTY >
<!ATTLIST ingredient id CDATA #REQUIRED>
<!ATTLIST ingredient name CDATA #REQUIRED>
<!ATTLIST ingredient proportion CDATA #REQUIRED>

=== larsnaesbye/mars-sim2/mars-sim/mars-sim-core/src/main/resources/conf/meals.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE meal-list SYSTEM "conf/dtd/meals.dtd">

<meal-list>

		<!--  A MAIN DISH will have dry mass with a total proportion of 0.8 while a SIDE DISH will have the remaining  proportion of 0.2 -->	
				
		<main-dish id="0" name="Kidney Bean Fried Rice" oil="0.05" salt="0.01" category="meal">
			<ingredient id="0" name="Kidney Bean" proportion="0.1"/>
			<ingredient id="1" name="White Rice" proportion="0.4"/>
			<ingredient id="2" name="Swiss Chard" proportion="0.1"/>
			<ingredient id="3" name="Green Bell Pepper" proportion="0.1"/>				
		</main-dish>				
	
		<main-dish id="1" name="Steamed Brown Rice" oil="0.05" salt="0.01" category="meal">					
			<ingredient id="0" name="Green Onion" proportion="0.2"/>
			<ingredient id="1" name="Celery" proportion="0.2"/>
			<ingredient id="2" name="Brown Rice" proportion="0.4"/>
		</main-dish>				
	
		<main-dish id="2" name="Cabbage Carrot Slaw Plate" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Cabbage" proportion="0.3"/>			
			<ingredient id="1" name="Carrot" proportion="0.4"/>
			<ingredient id="2" name="Swiss Chard" proportion="0.1"/>		
		</main-dish>				
				
		<main-dish id="3" name="Salsa Potato Salad" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Potato" proportion="0.4"/>				
			<ingredient id="1" name="Lettuce" proportion="0.29"/>
			<ingredient id="2" name="Green Onion" proportion="0.005"/>
			<ingredient id="3" name="Rice Vinegar" proportion="0.005"/>
			<ingredient id="4" name="Tomato" proportion="0.1"/>			
		</main-dish>		
	      	
		<main-dish id="4" name="Bean Sprout Garlic Stir Fry" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Soy Sprout" proportion="0.68"/>			
			<ingredient id="1" name="Green Onion" proportion="0.01"/>
			<ingredient id="2" name="Garlic" proportion="0.1"/>
			<ingredient id="3" name="Rice Vinegar" proportion="0.01"/>								
		</main-dish>				
	      	
		<main-dish id="5" name="Veggie Burger" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Veggie Patty" proportion="0.4"/>				
			<ingredient id="1" name="Wheat Bun" proportion="0.2"/>			
			<ingredient id="3" name="Lettuce" proportion="0.1"/>				
			<ingredient id="4" name="Tomato" proportion="0.1"/>	
		</main-dish>		
				
		<main-dish id="6" name="Sauteed Swiss Chard Fried Rice" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Swiss Chard" proportion="0.2"/>				
			<ingredient id="1" name="White Rice" proportion="0.4"/>
			<ingredient id="2" name="White Onion" proportion="0.1"/>				
			<ingredient id="3" name="Lettuce" proportion="0.05"/>				
			<ingredient id="4" name="Garlic" proportion="0.05"/>	
		</main-dish>		
				
		<main-dish id="7" name="Veggie Sandwich" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Veggie Patty" proportion="0.4"/>				
			<ingredient id="1" name="White Bread" proportion="0.15"/>			
			<ingredient id="2" name="Lettuce" proportion="0.1"/>				
			<ingredient id="3" name="Tomato" proportion="0.1"/>		
			<ingredient id="4" name="Peanut Butter" proportion="0.05"/>						
		</main-dish>		
				
		<main-dish id="8" name="Braised Celery Peanut Butter Dip" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Celery" proportion="0.5"/>							
			<ingredient id="1" name="Peanut Butter" proportion="0.05"/>	
			<ingredient id="2" name="Cucumber" proportion="0.25"/>									
		</main-dish>		
				      	
		<main-dish id="9" name="Tofu Menudo" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Tofu" proportion="0.35"/>				
			<ingredient id="1" name="Potato" proportion="0.1"/>
			<ingredient id="2" name="Peas" proportion="0.1"/>				
			<ingredient id="3" name="Tomato" proportion="0.1"/>
			<ingredient id="4" name="Green Bell Pepper" proportion="0.15"/>										
		</main-dish>		
				      	
		<main-dish id="10" name="Spaghetti" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Wheat Noodle" proportion="0.6"/>				
			<ingredient id="1" name="Green Bell Pepper" proportion="0.1"/>				
			<ingredient id="2" name="Tomato" proportion="0.1"/>									
		</main-dish>		

		<main-dish id="11" name="Hearty Quinoa Sprouts" oil="0.05" salt="0.001" category="meal">		
			<ingredient id="0" name="Quinoa Sprout" proportion="0.4"/>				
			<ingredient id="1" name="Ginger" proportion="0.15"/>				
			<ingredient id="2" name="Soy Sauce" proportion="0.05"/>
			<ingredient id="3" name="Cucumber" proportion="0.2"/>						
		</main-dish>	
		
		<main-dish id="12" name="Vegetarian Pho with Bean Sprout" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Rice Noodle" proportion="0.45"/>				
			<ingredient id="1" name="Ginger" proportion="0.1"/>				
			<ingredient id="2" name="Rice Vinegar" proportion="0.05"/>	
			<ingredient id="3" name="Soy Sprout" proportion="0.2"/>					
		</main-dish>	
		
		<main-dish id="13" name="Vegetarian Pizza" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Pizza Dough" proportion="0.5"/>				
			<ingredient id="1" name="Green Bell Pepper" proportion="0.1"/>			
			<ingredient id="2" name="Tomato" proportion="0.05"/>	
			<ingredient id="3" name="White Onion" proportion="0.1"/>
			<ingredient id="4" name="Morel Mushroom" proportion="0.05"/>
		</main-dish>
		
		<main-dish id="14" name="Spring Pasta with Fried Morels" oil="0.05" salt="0.01" category="meal">		
			<ingredient id="0" name="Morel Mushroom" proportion="0.1"/>				
			<ingredient id="1" name="Green Bell Pepper" proportion="0.1"/>
			<ingredient id="2" name="Cucumber" proportion="0.1"/>	
			<ingredient id="4" name="Wheat Noodle" proportion="0.5"/>					
		</main-dish>		
		
		
		<!--  SIDE DISH BELOW 
		      each side dish will have dry mass with proportion of 0.2
				TODO: will convert element tag to side dish -->	
		
		<main-dish id="15" name="Garlic Bread" oil="0.01" salt="0.005" category="meal">					
			<ingredient id="0" name="White Bread" proportion="0.16"/>	
			<ingredient id="1" name="Garlic" proportion="0.04"/>								
		</main-dish>		
		
		<main-dish id="16" name="French Fries" oil="0.01" salt="0.005" category="meal">		
			<ingredient id="0" name="French Fries" proportion="0.2"/>				
		</main-dish>		
		
		<main-dish id="17" name="Roasted Carrot Soup" oil="0.01" salt="0.005" category="meal">		
			<ingredient id="0" name="Carrot" proportion="0.05"/>				
			<ingredient id="1" name="Green Onion" proportion="0.05"/>
			<ingredient id="2" name="Celery" proportion="0.05"/>
			<ingredient id="3" name="Tomato" proportion="0.05"/>
		</main-dish>	
		
		<main-dish id="18" name="Miso Soup" oil="0.01" salt="0.005" category="meal">		
			<ingredient id="0" name="Sesame" proportion="0.005"/>
			<ingredient id="1" name="Tofu" proportion="0.19"/>
			<ingredient id="2" name="Soy Sauce" proportion="0.005"/>			
		</main-dish>	
		
		<main-dish id="19" name="Baby Carrots" oil="0.01" salt="0.005" category="meal">				
			<ingredient id="0" name="Carrot" proportion="0.2"/>	
		</main-dish>			

		<main-dish id="20" name="Peas and Onions" oil="0.01" salt="0.005" category="meal">				
			<ingredient id="0" name="Peas" proportion="0.1"/>	
			<ingredient id="4" name="White Onion" proportion="0.1"/>	
		</main-dish>					
							
	
</meal-list>
