=== larsnaesbye/mars-sim2/mars-sim/mars-sim-core/src/main/resources/conf/dtd/robots.dtd
<!ELEMENT robot-configuration (power-consumption-rate, starvation-start-time, min-air-pressure, 
min-temperature, max-temperature, freezing-time, robot-list)>
<!ELEMENT power-consumption-rate EMPTY>
<!ATTLIST power-consumption-rate value CDATA #REQUIRED>
<!ELEMENT starvation-start-time EMPTY>
<!ATTLIST starvation-start-time value CDATA #REQUIRED>
<!ELEMENT min-air-pressure EMPTY>
<!ATTLIST min-air-pressure value CDATA #REQUIRED>
<!ELEMENT min-temperature EMPTY>
<!ATTLIST min-temperature value CDATA #REQUIRED>
<!ELEMENT max-temperature EMPTY>
<!ATTLIST max-temperature value CDATA #REQUIRED>
<!ELEMENT freezing-time EMPTY>
<!ATTLIST freezing-time value CDATA #REQUIRED>
<!ELEMENT robot-list (robot*)>
<!ELEMENT robot (natural-attribute-list?, skill-list?)>
<!ATTLIST robot name CDATA #REQUIRED>
<!ATTLIST robot type CDATA #REQUIRED>
<!ATTLIST robot settlement CDATA #IMPLIED>
<!ATTLIST robot job CDATA #IMPLIED>
<!ELEMENT natural-attribute-list (natural-attribute*)>
<!ELEMENT natural-attribute EMPTY>
<!ATTLIST natural-attribute name CDATA #REQUIRED>
<!ATTLIST natural-attribute value CDATA #REQUIRED>
<!ELEMENT skill-list (skill*)>
<!ELEMENT skill EMPTY>
<!ATTLIST skill name CDATA #REQUIRED>
<!ATTLIST skill level CDATA #REQUIRED>

=== larsnaesbye/mars-sim2/mars-sim/mars-sim-core/src/main/resources/conf/robots.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE robot-configuration SYSTEM "conf/dtd/robots.dtd">

<robot-configuration>

	<!-- The average amount of electrical power needed each Martian Sol -->
	<power-consumption-rate value="1.0" />

	<!-- Number of sols a robot can go without food before starvation sets in -->
	<!-- Default: 1.0 -->
	<starvation-start-time value="1.0" />
	
	<!-- Minimum air pressure (Pa) a robt can withstand without harm -->
	<min-air-pressure value="500" />

	<!-- Minimum temperature (degrees celsius) a robot can withstand without harm -->
	<min-temperature value="-20.0" />

	<!-- Maximum temperature (degrees celsius) a robot can withstand without harm -->
	<max-temperature value="78.0" />

	<!-- Number of millisols a robot can survive below minimum temperature -->
	<!-- Note: 1 millisol = 88.77 seconds -->
	<freezing-time value="500.0" />

	<!-- List of robot type -->
	<robot-list>
		<robot name="ChefBot 001" type="ChefBot" settlement="Schiaparelli Point" job="Cook">
			<natural-attribute-list>
				<natural-attribute name="Strength" value="95"/>
				<natural-attribute name="Endurance" value="95"/>
				<natural-attribute name="Agility" value="40"/>
				<natural-attribute name="Teaching" value="10"/>
				<natural-attribute name="Academic Aptitude" value="95"/>
				<natural-attribute name="Experience Aptitude" value="95"/>
				<natural-attribute name="Stress Resilience" value="95"/>
				<natural-attribute name="Attractiveness" value="10"/>
				<natural-attribute name="Leadership" value="10"/>
				<natural-attribute name="Conversation" value="10"/>
			</natural-attribute-list>
			<skill-list>
				<skill name="Botany" level="1"/>
				<skill name="Mechanics" level="1"/>
				<skill name="EVA Operations" level="2"/>
				<skill name="Areology" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="Cooking" level="2"/>
			</skill-list>
		</robot>
		
		<robot name="GardenBot 002" type="GardenBot" settlement="Schiaparelli Point" job="Gardener">
			<natural-attribute-list>
				<natural-attribute name="Strength" value="95"/>
				<natural-attribute name="Endurance" value="95"/>
				<natural-attribute name="Agility" value="40"/>
				<natural-attribute name="Teaching" value="10"/>
				<natural-attribute name="Academic Aptitude" value="95"/>
				<natural-attribute name="Experience Aptitude" value="95"/>
				<natural-attribute name="Stress Resilience" value="95"/>
				<natural-attribute name="Attractiveness" value="10"/>
				<natural-attribute name="Leadership" value="10"/>
				<natural-attribute name="Conversation" value="10"/>
			</natural-attribute-list>
			<skill-list>
				<skill name="Botany" level="2"/>
				<skill name="Mechanics" level="1"/>
				<skill name="EVA Operations" level="2"/>
				<skill name="Areology" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>
		</robot>
		
		<robot name="RepairBot 003" type="RepairBot" settlement="Schiaparelli Point" job="Handyman">
			<natural-attribute-list>
				<natural-attribute name="Strength" value="95"/>
				<natural-attribute name="Endurance" value="95"/>
				<natural-attribute name="Agility" value="40"/>
				<natural-attribute name="Teaching" value="10"/>
				<natural-attribute name="Academic Aptitude" value="95"/>
				<natural-attribute name="Experience Aptitude" value="95"/>
				<natural-attribute name="Stress Resilience" value="95"/>
				<natural-attribute name="Attractiveness" value="10"/>
				<natural-attribute name="Leadership" value="10"/>
				<natural-attribute name="Conversation" value="10"/>
			</natural-attribute-list>
			<skill-list>
				<skill name="Botany" level="1"/>
				<skill name="Mechanics" level="2"/>
				<skill name="EVA Operations" level="2"/>
				<skill name="Areology" level="1"/>
				<skill name="Medicine" level="1"/>
				<skill name="Cooking" level="1"/>
			</skill-list>
		</robot>
		

		
	</robot-list>

</robot-configuration>
