<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE construction [
	<!ELEMENT construction (foundation-list, frame-list, building-list)>
	<!ELEMENT foundation-list (foundation*)>
	<!ELEMENT foundation (resource*, part*, vehicle*)>
	<!ATTLIST foundation name CDATA #REQUIRED>
	<!ATTLIST foundation width CDATA #REQUIRED>
	<!ATTLIST foundation length CDATA #REQUIRED>
	<!ATTLIST foundation north-south-alignment (width|length) #REQUIRED>		
	<!ATTLIST foundation base-level CDATA #REQUIRED>
	<!ATTLIST foundation constructable (true|false) #REQUIRED>
	<!ATTLIST foundation salvagable (true|false) #REQUIRED>
	<!ATTLIST foundation work-time CDATA #REQUIRED>
	<!ATTLIST foundation skill-required CDATA #REQUIRED>
	<!ELEMENT resource EMPTY>
	<!ATTLIST resource name CDATA #REQUIRED>
	<!ATTLIST resource amount CDATA #REQUIRED>
	<!ELEMENT part EMPTY>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part number CDATA #REQUIRED>
	<!ELEMENT vehicle (attachment-part*)>
	<!ATTLIST vehicle type CDATA #REQUIRED>
	<!ELEMENT attachment-part EMPTY>
	<!ATTLIST attachment-part name CDATA #REQUIRED>
	<!ELEMENT frame-list (frame*)>
	<!ELEMENT frame (resource*, part*, vehicle*)>
	<!ATTLIST frame name CDATA #REQUIRED>
	<!ATTLIST frame width CDATA #REQUIRED>
	<!ATTLIST frame length CDATA #REQUIRED>
	<!ATTLIST frame north-south-alignment (width|length) #REQUIRED>	
	<!ATTLIST frame base-level CDATA #REQUIRED>
	<!ATTLIST frame constructable (true|false) #REQUIRED>
	<!ATTLIST frame salvagable (true|false) #REQUIRED>
	<!ATTLIST frame work-time CDATA #REQUIRED>
	<!ATTLIST frame skill-required CDATA #REQUIRED>
	<!ATTLIST frame foundation CDATA #REQUIRED>
	<!ELEMENT building-list (building*)>
	<!ELEMENT building (resource*, part*, vehicle*)>
	<!ATTLIST building name CDATA #REQUIRED>
	<!ATTLIST building width CDATA #REQUIRED>
	<!ATTLIST building length CDATA #REQUIRED>
	<!ATTLIST building north-south-alignment (width|length) #REQUIRED>		
	<!ATTLIST building base-level CDATA #REQUIRED>
	<!ATTLIST building constructable (true|false) #REQUIRED>
	<!ATTLIST building salvagable (true|false) #REQUIRED>
	<!ATTLIST building work-time CDATA #REQUIRED>
	<!ATTLIST building skill-required CDATA #REQUIRED>
	<!ATTLIST building frame CDATA #REQUIRED>
]>

<construction>
	<foundation-list>
		<!-- work-time in sols, not millisols -->
		<foundation name="Surface Foundation 2x3" width="2.0" length="3.0" 
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.4" skill-required="1" >
			<resource name="concrete" amount="6.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 5x5" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="0.8" skill-required="1" >
			<resource name="concrete" amount="25.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 5x10" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.2" skill-required="1" >
			<resource name="concrete" amount="50.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<!-- surface foundation 7m_x_9m is setting for medium modular frame. work-time = 3.0 -->
		<foundation name="Surface Foundation 7x9" width="9.0" length="7.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.2" skill-required="1" >
			<resource name="concrete" amount="63.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 9x9" width="9.0" length="9.0" 
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="1.4" skill-required="1" >
			<resource name="concrete" amount="81.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 8x11" width="8.0" length="11.0" 
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="1.8" skill-required="1" >
			<resource name="concrete" amount="88.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Surface Foundation 12x18" width="18.0" length="12.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="2.4" skill-required="1" >
			<resource name="concrete" amount="216.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<foundation name="Subsurface Foundation 5x5x3" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="8.0" skill-required="1" >
			<resource name="concrete" amount="45.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Subsurface Foundation 5x10x3" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="12.0" skill-required="1" >
			<resource name="concrete" amount="80.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Subsurface Foundation 10x10x3" width="10.0" length="10.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="15.0" skill-required="1" >
			<resource name="concrete" amount="140.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Ramped Subsurface Foundation 15x18x5" width="18.0" length="15.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="20.0" skill-required="1" >
			<resource name="concrete" amount="369.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

		<foundation name="Shallow Borehole Drilling Site" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="10.0" skill-required="3" >
		 	<part name="bore drill bit" number="1" />
		 	<part name="bore drill pipe" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
				<attachment-part name="drilling rig" />
			</vehicle>
		</foundation>

		<foundation name="Deep Borehole Drilling Site" width="10.0" length="15.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="15.0" skill-required="4" >
		 	<part name="bore drill bit" number="4" />
		 	<part name="bore drill pipe" number="60" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
				<attachment-part name="drilling rig" />
			</vehicle>
		</foundation>

		<!-- Surface foundation with a variable width and length is dynamically set. -->
		<!-- (Used for hallway construction) -->
		<foundation name="Surface Foundation Variable Size" width="-1.0" length="-1.0"
		 north-south-alignment="length" base-level="0"
		 constructable="true" salvagable="true" work-time="1.0" skill-required="1" >
			<resource name="concrete" amount="100.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="soil compactor" />
			</vehicle>
		</foundation>

		<!-- Subsurface foundation with a variable width and length that is dynamically set. -->
		<!-- (Used for tunnel construction)	-->
		<foundation name="Subsurface Foundation Variable Size" width="-1.0" length="-1.0"
		 north-south-alignment="length" base-level="-1"
		 constructable="true" salvagable="true" work-time="2.0" skill-required="1" >
		 	<resource name="concrete" amount="150.0" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="bulldozer blade" />
				<attachment-part name="backhoe" />
			</vehicle>
		</foundation>

	</foundation-list>


	<frame-list>

		<frame name="Steel Frame Tower" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 5x5" >
			<resource name="acetylene" amount="1.0" />
			<resource name="concrete" amount="25.0" />
			<part name="insulation board" number="4" />				
			<part name="steel truss" number="20" />
			<part name="steel cable" number="6" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Small Steel Frame" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="1" foundation="Surface Foundation 5x5" >
			<resource name="acetylene" amount="1.0" />
			<resource name="concrete" amount="25.0" />
			<part name="insulation board" number="4" />			
			<part name="steel truss" number="10" />
			<part name="steel sheet" number="5" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Array Frame" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 5x10" >
			<resource name="acetylene" amount="1.5" />
			<resource name="concrete" amount="50.0" />
			<part name="insulation board" number="6" />				
			<part name="steel truss" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Brick Bin Frame" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="0.5" skill-required="1" foundation="Surface Foundation 2x3" >
			<resource name="concrete" amount="6.0" />
			<part name="brick" number="200" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Small Brick Shed Frame" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="1" foundation="Subsurface Foundation 5x5x3" >
			<resource name="concrete" amount="25.0" />
			<part name="brick" number="250" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Round Hab Frame" width="9.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 9x9" >
		 	<resource name="concrete" amount="81.0" />
			<resource name="acetylene" amount="2.0" />		 	
			<part name="aluminum sheet" number="10" />
			<part name="insulation board" number="10" />			
			<part name="steel truss" number="20" />
			<part name="steel post" number="8" />			
			<part name="steel sheet" number="10" />	
			<part name="plastic sheet" number="20" />					
			<part name="plastic pipe" number="50" />
			<part name="electrical wire" number="200" />
			<part name="wire connector" number="200" />
			<part name="power cable" number="20" />
			<part name="steel pipe" number="40" />
			<part name="gasket" number="40" />
			<part name="valve" number="10" />
			<part name="solar panel" number="4" />
		</frame>

		<frame name="Inflatable Frame" width="6.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 7x9" >
		 	<resource name="concrete" amount="54.0" />
			<resource name="acetylene" amount="1.25" />		 	
			<part name="aluminum sheet" number="10" />
			<part name="insulation board" number="10" />			
			<part name="steel truss" number="20" />
			<part name="steel post" number="5" />			
			<part name="steel sheet" number="10" />	
			<part name="plastic sheet" number="20" />
			<part name="plastic pipe" number="50" />
			<part name="electrical wire" number="80" />
			<part name="wire connector" number="80" />
			<part name="power cable" number="12" />
			<part name="steel pipe" number="40" />
			<part name="gasket" number="30" />
			<part name="valve" number="30" />			
		</frame>

		<frame name="Atmospheric Processor Frame" width="8.0" length="11.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" foundation="Surface Foundation 8x11" >
		 	<resource name="concrete" amount="88.0" />
			<resource name="acetylene" amount="1.0" />		 	
			<part name="aluminum sheet" number="10" />
			<part name="steel truss" number="20" />
			<part name="steel post" number="6" />			
			<part name="steel sheet" number="10" />
			<part name="plastic sheet" number="20" />			
			<part name="plastic pipe" number="50" />
			<part name="valve" number="20" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="10" />
			<part name="steel pipe" number="10" />
			<part name="gasket" number="18" />
		</frame>

		<frame name="Medium Modular Frame" width="7.0" length="9.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 7x9" >
		 	<resource name="concrete" amount="63.0" />
			<resource name="acetylene" amount="1.0" />		 	
			<part name="aluminum sheet" number="8" />
			<part name="insulation board" number="8" />			
			<part name="steel truss" number="16" />
			<part name="steel post" number="6" />			
			<part name="steel sheet" number="8" />
			<part name="plastic sheet" number="16" />
			<part name="plastic pipe" number="40" />
			<part name="valve" number="50" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="15" />
			<part name="gasket" number="15" />
		</frame>

		<frame name="Round Frame" width="7.0" length="7.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Surface Foundation 7x7" >
		 	<resource name="concrete" amount="49.0" />
			<resource name="acetylene" amount="1.0" />		 	
			<part name="aluminum sheet" number="6" />
			<part name="insulation board" number="7" />			
			<part name="steel truss" number="14" />
			<part name="steel post" number="6" />			
			<part name="steel sheet" number="7" />
			<part name="plastic sheet" number="14" />
			<part name="plastic pipe" number="36" />
			<part name="valve" number="45" />
			<part name="electrical wire" number="45" />
			<part name="wire connector" number="45" />
			<part name="power cable" number="13" />
			<part name="gasket" number="13" />
		</frame>
		
		<frame name="Large Greenhouse Frame" width="12.0" length="18.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.5" skill-required="3" foundation="Surface Foundation 12x18" >
		 	<resource name="concrete" amount="216.0" />
			<resource name="acetylene" amount="2.5" />		 	
			<part name="aluminum sheet" number="20" />
			<part name="insulation board" number="20" />			
			<part name="steel truss" number="30" />
			<part name="steel post" number="12" />			
			<part name="steel sheet" number="20" />
			<part name="plastic sheet" number="20" />	
			<part name="glass sheet" number="50" />
			<part name="plastic pipe" number="150" />
			<part name="valve" number="90" />
			<part name="gasket" number="90" />
			<part name="electrical wire" number="120" />
			<part name="wire connector" number="120" />
			<part name="power cable" number="30" />
		</frame>

		<frame name="Garage Frame" width="12.0" length="16.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.2" skill-required="2" foundation="Surface Foundation 12x18" >
		 	<resource name="concrete" amount="192.0" />
			<resource name="acetylene" amount="2.5" />			 	
			<part name="aluminum sheet" number="20" />
			<part name="insulation board" number="20" />			
			<part name="steel truss" number="30" />
			<part name="steel post" number="12" />			
			<part name="steel sheet" number="20" />
			<part name="plastic sheet" number="20" />
			<part name="plastic pipe" number="100" />
			<part name="valve" number="50" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="20" />
			<part name="gasket" number="40" />
		</frame>

		<frame name="Small Areothermal Well Frame" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" foundation="Shallow Borehole Drilling Site" >
			<resource name="concrete" amount="50.0" />
			<resource name="acetylene" amount="0.5" />				
			<part name="steel truss" number="10" />
			<part name="steel sheet" number="15" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Large Areothermal Well Frame" width="10.0" length="15.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.3" skill-required="3" foundation="Deep Borehole Drilling Site" >
			<resource name="concrete" amount="150.0" />
			<resource name="acetylene" amount="1.0" />				
			<part name="steel truss" number="20" />
			<part name="steel sheet" number="30" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Round Vaulted Brick Frame" width="10.0" length="10.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.2" skill-required="2" foundation="Subsurface Foundation 10x10x3" >
			<resource name="concrete" amount="100.0" />
			<part name="brick" number="1200" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Large Garage Brick Frame" width="15.0" length="18.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.5" skill-required="3" foundation="Ramped Subsurface Foundation 15x18x5" >
			<resource name="concrete" amount="270.0" />
			<resource name="acetylene" amount="2.5" />				
			<part name="brick" number="3600" />
			<part name="aluminum sheet" number="50" />
			<part name="insulation board" number="50" />			
			<part name="steel truss" number="30" />
			<part name="steel post" number="12" />			
			<part name="steel sheet" number="50" />
			<part name="plastic sheet" number="20" />
			<part name="plastic pipe" number="100" />
			<part name="valve" number="50" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="power cable" number="20" />
			<part name="gasket" number="40" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<frame name="Vaulted Glass Brick Frame" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" foundation="Subsurface Foundation 5x10x3" >
			<resource name="concrete" amount="50.0" />
			<resource name="acetylene" amount="0.5" />				
			<part name="brick" number="700" />
			<part name="aluminum sheet" number="10" />
			<part name="insulation board" number="10" />			
			<part name="steel truss" number="8" />
			<part name="steel post" number="4" />						
			<part name="glass sheet" number="10" />
			<part name="plastic pipe" number="7" />
			<part name="valve" number="5" />
			<part name="gasket" number="5" />
			<part name="electrical wire" number="6" />
			<part name="wire connector" number="6" />
			<part name="power cable" number="3" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

		<!-- Note hallway frame length is variable. -->
		<frame name="Hallway frame" width="2.0" length="-1.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="0.1" skill-required="1" foundation="Surface Foundation Variable Size" >
			<resource name="concrete" amount="2.0" />
			<resource name="acetylene" amount="0.25" />	
			<part name="insulation board" number="4" />						
			<part name="steel post" number="3" />
		</frame>

		<!-- Note brick tunnel frame length is variable. -->
		<frame name="Brick Tunnel Frame" width="3.0" length="-1.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="0.2" skill-required="1" foundation="Subsurface Foundation Variable Size" >
			<resource name="concrete" amount="3.0" />			
			<part name="brick" number="90" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</frame>

	</frame-list>

	<building-list>

		<building name="Wind Turbine" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" frame="Steel Frame Tower" >
			<part name="aerogel tile" number="10" />		 
			<part name="wind turbine blade" number="4" />
			<part name="turbine generator" number="1" />
			<part name="power cable" number="6" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>

		<building name="Solar Photovoltaic Array" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="2" frame="Array Frame" >
			<part name="aerogel tile" number="16" />
			<part name="solar panel" number="6" />
			<part name="power cable" number="2" />
			<part name="Stepper Motor" number="4" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>

		<building name="Solar Thermal Collector" width="5.0" length="10.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" frame="Array Frame" >
			<resource name="water" amount="200.0" />
			<part name="aerogel tile" number="32" />
			<part name="solar parabolic mirror" number="3" />
			<part name="power cable" number="2" />
			<part name="glass tube" number="6" />
			<part name="steel pipe" number="10" />
			<part name="Stepper Motor" number="4" />
			<part name="heat pump" number="1" />
			<part name="water pump large" number="2" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<part name="water tank" number="1" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>

		<building name="Methane Power Generator" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" frame="Small Steel Frame" >
			<part name="aerogel tile" number="65" />		 
			<part name="methane fuel cell stack" number="4" />
			<part name="valve" number="6" />
			<part name="gasket" number="6" />
			<part name="plastic tubing" number="6" />
			<part name="power cable" number="6" />
			<part name="electrical wire" number="20" />
			<part name="wire connector" number="20" />
			<part name="fuel tank" number="5" />
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>

		<building name="Cement Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="20" />
		</building>
	
		<building name="Chemical Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>
			
		<building name="Concrete Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />			
		</building>
		
		<building name="Fuel Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Gas Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>
		
		<building name="Ice Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Metal Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Lime Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Ore Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Regolith Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Sand Storage" width="2.0" length="3.0"
		 north-south-alignment="length" base-level="0" constructable="true"
		 salvagable="true" work-time=".25" skill-required="1" frame="Brick Bin Frame" >
			<resource name="concrete" amount="60.0" />
			<part name="aerogel tile" number="32" />
		</building>

		<building name="Manufacturing Shed" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="0.5" skill-required="3" frame="Small Brick Shed Frame" >
			<resource name="concrete" amount="75.0" />
			<part name="aerogel tile" number="90" />
			<part name="steel pipe" number="3" />
			<part name="plastic pipe" number="10" />
			<part name="valve" number="10" />
			<part name="gasket" number="10" />
			<part name="plastic tubing" number="10" />
			<part name="power cable" number="10" />
			<part name="electrical wire" number="50" />
			<part name="wire connector" number="50" />
			<part name="plastic bottle" number="25" />
			<part name="Motor 10 kW" number="1" />
			<part name="brick" number="100" />
			<part name="gas tank" number="3" />
			<part name="air duct" number="5" />			
			<vehicle type="light utility vehicle" >
				<attachment-part name="crane boom" />
			</vehicle>
		</building>

		<building name="Bunkhouse" width="5.0" length="5.0"
		 north-south-alignment="length" base-level="-1" constructable="true"
		 salvagable="true" work-time="1.0" skill-required="3" frame="Small Brick Shed Frame" >
		 	<resource name="cement" amount="75.0" />
		 	<resource name="concrete" amount="57.0" />
			<part name="aerogel tile" number="90" />
			<part name="window" number="2" />				
			<part name="steel pipe" number="3" />
			<part name="plastic pipe" number="4" />
			<part name="valve" number="5" />
			<part name="gasket" number="5" />