<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE mineral-concentrations [
	<!ELEMENT mineral-concentrations (mineral*)>
	<!ELEMENT mineral (locale-list)>
	<!ATTLIST mineral name CDATA #REQUIRED>
	<!ATTLIST mineral color CDATA #REQUIRED>
	<!ATTLIST mineral frequency (common|uncommon|rare|very_rare) #REQUIRED>
	<!ELEMENT locale-list (locale+)>
	<!ELEMENT locale EMPTY>
	<!ATTLIST locale name (volcanic|sedimentary|plutonic|crater) #REQUIRED>
]>

<!-- List of all mineral concentrations that can be mined. -->
<mineral-concentrations>

	<!-- 
		
		See https://www.mars.asu.edu/data/ for mineral map
		
		
		A. Brave browser
		
		Given the Martian environment and the presence of clay minerals, it’s likely that plutonic rocks 
		on Mars would contain minerals such as:

		1. Plagioclase feldspar: a common mineral in Gabbro, a dark-colored, coarsely-grained plutonic rock 
		   (as described in the search result)
		2. Pyroxenes (including augite): also present in Gabbro, these minerals are common in mafic plutonic rocks
		3. Micas: a group of minerals that can form in plutonic rocks, particularly in those with a high silica content
		4. Clay minerals: abundant on Mars, these minerals would likely be present in Martian plutonic rocks, 
		   potentially in the form of phyllosilicates (e.g., montmorillonite, kaolinite)
		
		
		B. https://www.thoughtco.com/plutonic-rocks-1440845
		   https://www.thoughtco.com/about-igneous-rocks-1438950
		
		There are three main types of igneous rocks. Rock formed of lava is called extrusive, rock from 
		shallow magma is called intrusive, and rock from deep magma is called plutonic. 
		
		The deeper the magma, the slower it cools, and it forms larger mineral crystals. 
		
		The name "plutonic" refers to Pluto, Roman god of wealth and the underworld; pluto's origins also 
		come from "wealth," or "rich one," which could refer to the precious metals present in the Earth and 
		in rocks. Gold and silver are found in veins in plutonic rocks, which are formed from the intrusions 
		of the magma.

		In contrast, volcanic rocks are formed by magma above ground. Their crystals are evident only through
		an examination under a microscope.
		
		Plutonic rock is holocrystalline—every bit of mineral matter is in a crystalline form, and there is 
		no glassy fraction. Typical plutonic rocks look like granite.
		
		Whereas plutonic rocks form continents, basalt lies in the crust underneath the oceans.
		
		Rocks are extrusive if it did erupt.
	-->

	<!-- Chalcopyrite is a copper sulfide mineral. -->
	<!-- http://en.wikipedia.org/wiki/Chalcopyrite -->
	<!-- color: RGB color in the form of a sharp # symbol followed by a 6-digit alphanumeric code -->
	<!-- frequency:  how common are the mineral concentrations ? -->
	<!--             "common", "uncommon", "rare", "very_rare" -->
	<!-- brass yellow. Copper content. RGB color: ##ffee00 (light yellow) -->
	<mineral name="Chalcopyrite" color="#ffee00" frequency="uncommon">
		<locale-list>
			<!-- locale topographical regions the mineral is located. -->
			<!-- Valid values: "volcanic" (extrusive igneous), "plutonic" (intrusive igneous), "sedimentary", "crater" -->
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
		
	<!-- Goethite is an iron ore that has metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Goethite -->
	<!-- Yellow-brown, Reddish-brown, Dark brown. iron(III) oxide-hydroxide named in honor to the poet Goethe. RGB color: #BAAA47 (pale gold) -->
	<mineral name="Goethite" color="#BAAA47" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Hematite is an iron ore. -->
	<!-- http://en.wikipedia.org/wiki/Hematite -->	
	<!-- 
		1. https://science.nasa.gov/science-news/science-at-nasa/2001/ast28mar_1
		
		In 1998, an infrared spectrometer on NASA's Mars Global Surveyor (MGS) spacecraft 
		detected a substantial deposit of gray hematite near the Martian equator, in a 500 
		km-wide region called Sinus Meridiani. 
		
		The discovery raised the tantalizing possibility that hot springs were once active
		on Mars.
		
		Gray hematite has the same chemical formula (Fe2O3) as its rusty-red cousin, but 
		a different crystalline structure. Red rust is fine and powdery; typical grains 
		are hundreds of nanometers to a few microns across. Gray hematite crystals are 
		larger, like grains of sand.

		Red and gray iron oxides on Mars are different forms of the same 
		mineral. 
		
		Ground up the gray hematite into a fine powder it would turn red because the 
		smaller grains scatter red light.

		The coarse-grained structure of gray hematite is important because "to get that 
		kind of coarsening of the crystallinity, you would need to have a reasonable 
		amount of water available" where the hematite formed.
		
		Some of them, like carbonates, would also indicate that standing bodies of 
		water were present on the surface.
		
		Hematite minerals, on the other hand, might have been formed by hydrothermal
		water deep underground.
		
		2. https://www.psi.edu/sites/default/files/newsletter/winter02/Winter2002.pdf
			
		The mineral the TES instrument unequivocally identified is gray hematite 
		(Fe2O3), an oxide mineral that occurs on Earth as well as Mars, whose 
		chemistry is similar to that of common rust. 
		
		The hematite found on Mars occurs in both fine-grained and coarse-grained 
		varieties.  Fine-grained hematite (whose grain diameters are <5-10 microns)
		gives Mars its red color, which is why Mars is called the “Red Planet”.  
		 
		This fine-grained hematite is dispersed within the copious dust that gets 
		blown around the planet during the seasonal Martian dust storms and is 
		seen as the lighter-colored regions on Mars.  In contrast, coarser-grained
		hematite (>10 micron-diameter grains) is gray, not red like the finer-
		grained hematite in the Martian dust, since the finer grains scatter the
		red end of the solar spectrum.
		  
		A global investigation of Mars by the TES instrument has led to 
		identification of only three main areas of gray hematite exposed at the 
		surface of the entire planet.  
		
		These gray hematite deposits all occur in darker regions on Mars near 
		the equator including an area called Sinus Meridiani, in a large impact
		crater called Aram, and within the Valles Marineris canyon system.  
		
		It is possible that the finegrained hematite originated through weathering
		of gray hematite like those three areas near the equator.
		
		It is a common rock-forming mineral found in sedimentary, metamorphic, 
		and igneous rocks at locations throughout the world.
	-->
	<!-- Grey, rust red, brown. Fe2O3. has impurities. RGB color: #B05508 (rust orange, slightly red) -->
	<mineral name="Hematite" color="#B05508" frequency="common">
		<locale-list>
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
		
	<!-- Kamacite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Kamacite 
	     Derived from the Greek root καμακ- "kamak" or κάμαξ "kamaks", meaning vine-pole.-->
	<!-- dark brass, black, gray Fe2O3. has impurities. RGB color: #6d6329 (dull mud brown slightly orange) -->
	<mineral name="Kamacite" color="#6d6329" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>
	
		
	<!-- Magnesite is a magnesium carbonate with metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnesite -->
	<!-- 
		Magnesite is a mineral with the chemical formula MgCO3 
		(magnesium carbonate). Iron, manganese, cobalt, and nickel may occur 
		as admixtures, but only in small amounts.
	
		1. http://en.wikipedia.org/wiki/Magnesite 
		
	    Magnesite was detected in meteorite ALH84001 and on planet Mars itself. 
	    Magnesite was identified on Mars using infrared spectroscopy from satellite 
	    orbit. Near Jezero Crater, Mg-carbonates have been detected and reported to
	    have formed in lacustrine environment prevailing there.[28] Controversy 
	    still exists over the temperature of formation of these carbonates. 
	    
	    Low-temperature formation has been suggested for the magnesite from the 
	    Mars-derived ALH84001 meteorite.

		Magnesium-rich olivine (forsterite) favors production of magnesite from 
		peridotite. Iron-rich olivine (fayalite) favors production of magnetite-
		magnesite-silica compositions.
	-->
	<!-- white. yellow, grey, blue. RGB color: #FFFFFF (white) -->
	<mineral name="Magnesite" color="#FFFFFF" frequency="rare">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	<!-- Magnetite is an iron ore with volcanic and metamorphic origins. -->
	<!-- http://en.wikipedia.org/wiki/Magnetite -->
	<!-- 
		1. https://www.nature.com/articles/s41561-018-0203-8
		
		Experiments show that pH variations within anoxic basaltic waters trigger 
		a series of mineral transformations that rapidly generate magnetite and 
		H2(aq). Magnetite continues to form through this mechanism despite high 
		partial pressure of carbon dioxide (pCO2) and supersaturation with respect
		to Fe-carbonate minerals. Reactive transport simulations that incorporate 
		these experimental data show that groundwater infiltration into a lake 
		equilibrated with a CO2-rich atmosphere can trigger the production of 
		both magnetite and H2(aq) in the mudstones. H2(aq), generated at 
		concentrations that would readily exsolve from solution, is capable of 
		increasing annual mean surface temperatures above freezing in CO2-dominated
		atmospheres. We therefore suggest that magnetite authigenesis could have
		provided a short-term feedback for stabilizing liquid water, as well as
		a principal feedstock for biologically relevant chemical reactions, at 
		the early Martian surface.
		  
		2. https://www.pnas.org/doi/10.1073/pnas.241387898
		
		The case for former Martian life now rests on the identification of a small
		subset of the magnetite crystals in ALH84001 as biogenic in origin. 
	-->
	<!-- black, dark grey, silver, brown. RGB color: #86869b (dull blue/silver grey) -->
	<mineral name="Magnetite" color="#86869b" frequency="rare">
		<locale-list>
			<locale name="volcanic" />
			<locale name="sedimentary" />
		</locale-list>
	</mineral>

	
	<!-- Olivine is a magnesium iron silicate found in meteorites. -->
 	<!-- 
 		1. https://zenodo.org/record/1230836
 		
 		30,000-square-kilometer area rich in olivine in the Nili Fossae region of Mars. 
 		Nili Fossae has been interpreted as a complex of grabens and fractures related to 
 		the formation of the Isidis impact basin.
 	
 		2. http://en.wikipedia.org/wiki/Olivine 
 	
 		Mg-rich olivine has also been discovered in meteorites, on the Moon and Mars, falling 
 		into infant stars, as well as on asteroid 25143 Itokawa.
 		
 		3. https://en.wikipedia.org/wiki/Composition_of_Mars
 		
     	The mineral olivine occurs all over the planet, but some of the largest concentrations 
     	are in Nili Fossae, an area containing Noachian-aged rocks. Another large olivine-rich
     	outcrop is in Ganges Chasma, an eastern side chasm of Valles Marineris. 
     	
     	Olivine weathers rapidly into clay minerals in the presence of liquid water. 
     	Therefore, areas with large outcroppings of olivine-bearing rock indicate that liquid 
     	water has not been abundant since the rocks formed.
     	
     	Magnesium Iron Silicate (Mg,Fe)2SiO4. A type of nesosilicate or orthosilicate
 	-->
	<!-- yellow to yellow-green color, occasionally ranging to pale olive green. RGB color: #a4d629 (greenish yellow) -->
	<mineral name="Olivine" color="#a4d629" frequency="uncommon">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>

	
	<!-- Malachite is a copper carbonate mineral. -->
	<!-- http://en.wikipedia.org/wiki/Malachite 
	
	     Derives (via Latin: molochītis, Middle French: melochite, and Middle English melochites) from Greek Μολοχίτης λίθος
	     molochites lithos, "mallow-green stone", from μολόχη molochē, variant of μαλάχη malāchē, "mallow".
	     
	     The mineral was given this name due to its resemblance to the leaves of the mallow plant.[7] Copper (Cu2+) gives
	     malachite its green color.
	-->
	<!-- vibrant, bluish-green color with a distinctive banded or striated pattern. RGB color: #22dda1 (light bluish green) -->
	<mineral name="Malachite" color="#22dda1" frequency="uncommon">
		<locale-list>
			<locale name="sedimentary" />
			<locale name="volcanic" />
		</locale-list>
	</mineral>
	
	<!-- Pyroxenes are a group of important rock-forming inosilicate minerals found in many igneous and metamorphic rocks. -->
	<!-- https://en.wikipedia.org/wiki/Pyroxene													-->
	<!-- Pyroxenes have the general formula XY(Si,Al)2O6, where X represents calcium (Ca), sodium (Na), iron (Fe(II)) or 
	     magnesium (Mg) and more rarely zinc, manganese or lithium, and Y represents ions of smaller size, such as chromium (Cr),
	     aluminium (Al), magnesium (Mg), cobalt (Co), manganese (Mn), scandium (Sc), titanium (Ti), vanadium (V) or even 
	     iron (Fe(II) or Fe(III)).    
	     
	     The name pyroxene is derived from the Ancient Greek words for 'fire' (πυρ, pur) and 'stranger' (ξένος, xénos). 
	     Pyroxenes were so named due to their presence in volcanic lavas, where they are sometimes found as crystals embedded 
	     in volcanic glass; it was assumed they were impurities in the glass, hence the name meaning "fire stranger". 
	     However, they are simply early-forming minerals that crystallized before the lava erupted.  -->
	     
	<!-- RGB color: #08580d (dark green) -->
	<mineral name="Pyroxene" color="#08580d" frequency="common">
		<locale-list>
			<locale name="volcanic" />
			<locale name="plutonic" />
		</locale-list>
	</mineral>
	
	<!-- Sylvite is a salt concentration of potassium chloride. -->
	<!-- http://en.wikipedia.org/wiki/Sylvite 
	     
	     Rock salt. Potassium Chloride (KCl) in natural mineral form. 
	     
	     It forms crystals in the isometric system very similar to normal rock salt, halite (NaCl). 
	-->
	<!-- Colorless to white
		 Pale gray
		 Pale blue
		 May be yellowish red to red due to hematite inclusions
	 	 RGB color: #bdcddc (pale grey with slightly pale blue) -->
	<mineral name="Sylvite" color="#bdcddc" frequency="common">
		<locale-list>
			<locale name="sedimentary" />
		</locale-list>
	</mineral>
	
	
	
	<!-- Taenite is an iron-nickel mineral found in meteorites. -->
	<!-- http://en.wikipedia.org/wiki/Taenite 
	      Fe-Ni meteorite minerals														-->
	<!-- metallic grayish to white color. It is an opaque mineral, meaning it does not transmit light, and its 
	     grayish-white hue is a characteristic feature of this Fe-Ni alloy. 
	     Opaque. Color: Silver-white to grayish white.   Luster: Metallic.    
	     RGB color: #E4E6E8 (pale silver white) -->
	<mineral name="Taenite" color="#E4E6E8" frequency="common">
		<locale-list>
			<locale name="crater" />
		</locale-list>
	</mineral>


	<!-- jarosite, Plagioclase, Feldspar, High-Ca Pyroxene, Low-Ca Pyroxene, Quartz,
    Amphibole, Silicates -->
	
	<!-- 
		A. https://en.wikipedia.org/wiki/Amphibole
		
		   Amphibole is a group of inosilicate minerals, forming prism or needlelike crystals, 
		   composed of double chain SiO4 tetrahedra, linked at the vertices and generally containing 
		   ions of iron and/or magnesium in their structures. 
		   
		   Amphiboles can be green, black, colorless, white, yellow, blue, or brown. 
		
		1. Amphibole is a group of hydrous minerals that occur in a wide
		   range of rock types, including those found on Mars. 
		
		2. Amphiboles are a major group of dark-colored rock-forming inosilicate minerals composed of 
		   double chain SiO4 tetrahedra linked at the vertices and generally containing ions of iron 
		   and/or magnesium in their structures.

		3. On Mars, Amphiboles are likely to be present in Martian rocks that have undergone metamorphism, 
		   such as those found in the Martian crust or upper mantle. 
		
		4. The presence of Amphiboles on Mars is supported by the fact that they are common in metamorphic 
		   and igneous rocks on Earth, and Martian rocks have undergone similar geological processes.

		5. Like pyroxenes, amphiboles are classified as inosilicate (chain silicate) minerals. 
		   However, the pyroxene structure is built around single chains of silica tetrahedra while 
		   amphiboles are built around double chains of silica tetrahedra.
		   
	-->
	
	
</mineral-concentrations>