<?xml version = "1.0" encoding = "UTF-8" standalone = "yes" ?>
<!DOCTYPE part-list [
	<!ELEMENT part-list (part*)>
	<!ELEMENT part (description?,maintenance-entity-list?)>
	<!ATTLIST part name CDATA #REQUIRED>
	<!ATTLIST part mass CDATA #REQUIRED>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT maintenance-entity-list (entity*)>
	<!ELEMENT entity EMPTY>
	<!ATTLIST entity name CDATA #REQUIRED>
	<!ATTLIST entity probability CDATA #REQUIRED>
	<!ATTLIST entity max-number CDATA #REQUIRED>
]>

<part-list>
		<!--  Note: mass in kg can be a decimal number. -->
		<!--  Note: both probability and max-number must be a whole integer and without decimal places. -->
	<part name="airleak patch" mass=".2">
		<description>Plastic and adhesive patch for airleak.</description>
<!-- 		<maintenance-entity-list>
			<entity name="life support" probability="5" max-number="4" />
			<entity name="rover" probability="5" max-number="2" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="farming" probability="5" max-number="4" />
		</maintenance-entity-list>
-->		
	</part>
	<part name="fire extinguisher" mass="3" />

	<part name="gasket" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="farming" probability="5" max-number="6" />
			<entity name="living accommodations" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="2" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="valve" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="2" />
			<entity name="farming" probability="5" max-number="3" />
			<entity name="living accommodations" probability="5" max-number="2" />
			<entity name="manufacture" probability="5" max-number="3" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="1" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="epoxy resin bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="6" />
			<entity name="farming" probability="5" max-number="12" />
			<entity name="living accommodations" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="6" />
			<entity name="eva suit" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="spark plug" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="coolant bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="electrical wire" mass=".1">
		<maintenance-entity-list>
			<entity name="building" probability="5" max-number="6" />		
			<entity name="vehicle" probability="5" max-number="6" />
			<entity name="power generation" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="4" />
			<entity name="settlement" probability="5" max-number="8" />
		</maintenance-entity-list>
	</part>

	<part name="power cable" mass="1">
		<maintenance-entity-list>
			<entity name="power generation" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="wire connector" mass=".005">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="6" />
			<entity name="power generation" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="plastic tubing" mass=".1">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="farming" probability="5" max-number="10" />
			<entity name="manufacture" probability="5" max-number="10" />
		</maintenance-entity-list>
	</part>

	<part name="lubricant bottle" mass=".2">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="radio antenna" mass="2.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="satellite dish" mass="10.0">
		<maintenance-entity-list>
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="timing belt" mass=".2">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="communications circuit board" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="communication" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="navigation circuit board" mass=".5">
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>


	<part name="steel canister" mass="10.0" />

	<part name="bottle" mass=".1" />

	<part name="iron ingot" mass="7.0" />

	<part name="steel ingot" mass="5.0" />

	<part name="aluminum ingot" mass="1.0" />
	
	<part name="steel sheet" mass="7.8" >
		<description>A density of 7.8 g/cm3. 1m x 1m x 1mm sheet of steel</description>
	</part>


	<part name="iron sheet" mass="7.85" >
		<description>A density of 7.85 g/cm3. 1m x 1m x 1mm sheet of iron</description>
	</part>
	
	<!-- based on https://www.gigacalculator.com/calculators/metal-weight-calculator.php  -->
	<part name="aluminum sheet" mass="2.72" >
		<description>A density of 2.72 g/cm3. 1m x 1m x 1mm sheet of aluminum</description>
	</part>
	
	<part name="copper sheet" mass="8.94">
		<description>A density of 8.94 g/cm3. 1m x 1m x 1mm sheet of copper</description>
	</part>

	<!-- 1kg spool of thin copper wire -->
	<part name="copper wire" mass="1.0" />
	
	<!-- 1kg spool of thick steel wire -->
	<part name="steel wire" mass="1.0" />

	<!-- 5kg spool of thick steel cable -->
	<part name="steel cable" mass="5.0" />

	<!-- 1kg spool of thin aluminum wire -->
	<part name="aluminum wire" mass="1.0" />

	<part name="steel pipe" mass="0.882">
	<description>A density of 7.8 g/cm3. length of 1m. Thinkcness of 2mm. Diameter of 20 mm</description>
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="2" />
			<entity name="manufacture" probability="1" max-number="2" />
			<entity name="rover" probability="1" max-number="1" />
			<entity name="settlement" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="iron pipe" mass="0.888">
		<description>A density of 7.85 g/cm3. length of 1m. Thinkcness of 2mm. Diameter of 20 mm</description>
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="2" />
			<entity name="manufacture" probability="1" max-number="2" />
			<entity name="rover" probability="1" max-number="1" />
			<entity name="settlement" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="copper pipe" mass="	1.011">
		<description>A density of 8.94 g/cm3. length of 1m. Thinkcness of 2mm. Diameter of 20 mm</description>
		<maintenance-entity-list>
			<entity name="living accommodations" probability="2" max-number="1" />
			<entity name="farming" probability="2" max-number="2" />
			<entity name="manufacture" probability="2" max-number="2" />
			<entity name="settlement" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>
	
	<part name="plastic pipe" mass="1.0">
		<maintenance-entity-list>
			<entity name="living accommodations" probability="5" max-number="2" />
			<entity name="farming" probability="5" max-number="4" />
			<entity name="manufacture" probability="5" max-number="2" />
			<entity name="rover" probability="5" max-number="1" />
			<entity name="settlement" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>
	
	<!-- 1kg spool of thin fiberglass -->
	<part name="fiberglass" mass="1.0" />

	<!-- 1m x 1m square of woven fiberglass cloth -->
	<part name="fiberglass cloth" mass=".1" />

	<!-- 1m x 1m square of thin plastic sheet -->
	<part name="plastic sheet" mass=".1" />

	<!-- 1m x 1m x 1cm square of glass  -->
	<part name="glass sheet" mass="26.0" />

<!-- <part name="eva suit" mass="2.0" />

	Extravehicular Mobility Unit (EMU). Extravehicular Activity Suit Systems Design How to Walk, Talk, 
	and Breathe on Mars http://www.lpi.usra.edu/publications/reports/CB-979/cornell.pdf 

-->
	
	<part name="eva helmet" mass="1.0" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="helmet visor" mass="0.5" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="counter pressure suit" mass="1.0" >
		<description>Spandex inner EVA suit for counter pressure.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="coveralls" mass="1.0" >
		<description>Outer EVA suit with insulative liner.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="suit heating unit" mass="0.25">
		<maintenance-entity-list>
			<entity name="eva suit" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva gloves" mass="0.1" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva boots" mass="2.0" >
		<description>steel soled and tipped.  Fiberglass insulated.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva pads" mass="0.5" >
		<description>steel plate with fiberglass insulation.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva backpack" mass="5.0" >
		<description>The backpack is the most crucial part of the Portable Life-Support System (PLSS).
		It is made with polyethylene and a steel frame.</description>
		<maintenance-entity-list>
			<entity name="eva suit" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva antenna" mass=".05" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva battery" mass="2.5" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="eva radio" mass="0.25" >
		<maintenance-entity-list>
			<entity name="eva suit" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="large vehicle frame" mass="5000.0">
		<description>Heavy steel frame</description>
	</part>

	<part name="rover chassis panel" mass="100.0" >
		<description>Reinforced fiberglass panels.</description>
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="10" />
		</maintenance-entity-list>
	</part>

	<part name="rover battery" mass="50.0">
		<description>This rechargeable battery module provide auxiliary electric power
		to the vehicle.</description>
		<maintenance-entity-list>
			<entity name="rover" probability="2" max-number="4" />
			<entity name="light utility vehicle" probability="2" max-number="1" />
			<entity name="delivery drone" probability="2" max-number="1" />			
		</maintenance-entity-list>
	</part>
	
	<part name="rover wheel" mass="15.0">
		<description>Rover wheels are made of steel and steel wire.</description>
		<maintenance-entity-list>	
			<entity name="rover" probability="5" max-number="6" />
		</maintenance-entity-list>
	</part>
	
	<part name="rover windshield" mass="100.0" >
		<maintenance-entity-list>
			<entity name="rover" probability=".5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="rover window" mass="50.0" >
		<maintenance-entity-list>
			<entity name="rover" probability=".5" max-number="5" />
		</maintenance-entity-list>
	</part>

	<part name="rover generator" mass="500.0" >
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="fuel power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="large motor" mass="100.0" >
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="4" />
			<entity name="wind power source" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="rover control panel" mass="100.0" >
		<description>Made from polyethelene and reinforced fiberglass.</description>
		<maintenance-entity-list>
			<entity name="rover" probability=".5" max-number="1" />
		</maintenance-entity-list>
	</part>


	<part name="gas tank" mass="20.0" >
	 	<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="life support" probability="1" max-number="1" />
			<entity name="fuel heating source" probability="3" max-number="1" />
			<entity name="cooking" probability="3" max-number="1" />	
			<entity name="farming" probability="3" max-number="5" />					
		</maintenance-entity-list>
	</part>

	<part name="water tank" mass="20.0" >
	 	<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />
			<entity name="life support" probability="1" max-number="1" />
			<entity name="fuel heating source" probability="5" max-number="1" />
			<entity name="cooking" probability="5" max-number="1" />		
			<entity name="farming" probability="5" max-number="5" />				
		</maintenance-entity-list>
	</part>

	<part name="fuel tank" mass="50.0" >		
	<description>for storing methane</description>
		<maintenance-entity-list>
			<entity name="rover" probability="5" max-number="1" />		
			<entity name="life support" probability="1" max-number="1" />
			<entity name="fuel heating source" probability="5" max-number="1" />
			<entity name="cooking" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="heating element" mass="1.0" >
		<description>The heating element is a thermofoil conductive
		electrical element embedded in a thin Kapton substrate.</description>
		<maintenance-entity-list>
			<entity name="life support" probability="1" max-number="1" />
			<entity name="rover" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="pneumatic drill" mass="25.0">
		<description>Attachment part for LUV. A pneumatic hand for lifting.</description>
	</part>

	<part name="backhoe" mass="35.0" >
		<description>Attachment part for LUV. An excavating equipment with a digging bucket on the end of a two-part articulated arm</description>
	</part>

	<part name="bulldozer blade" mass="40.0">
		<description>Attachment part for LUV. A bulldozer blade (possible use for new structures).</description>
	</part>

	<part name="soil compactor" mass="100.0">
		<description>Attachment part for LUV. A drum roller that applied stress to a soil</description>
	</part>

	<part name="crane boom" mass="75.0">
		<description>Attachment part for LUV. A long, telescopic or fixed arm for moving objects</description>
	</part>

	<part name="small motor" mass="10.0" >
		<maintenance-entity-list>
			<entity name="robot" probability="1" max-number="1" />
			<entity name="light utility vehicle" probability="1" max-number="4" />			
			<entity name="delivery drone" probability="1" max-number="4" />				
		</maintenance-entity-list>
	</part>

	<part name="small vehicle frame" mass="250.0" />

	<part name="small wheel" mass="10.0" >
		<maintenance-entity-list>
			<entity name="" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="utility vehicle control panel" mass="10" >
		<maintenance-entity-list>
			<entity name="light utility vehicle" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="steel truss" mass="50.0">
		<description>Large steel bar used for construction.</description>
	</part>

	<part name="steel post" mass="5.0">
		<description>A small, light steel bar used for construction.</description>
	</part>

	<part name="wind turbine blade" mass="2.0" >
		<description>Blade for a wind turbine.</description>
		<maintenance-entity-list>
			<entity name="wind power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="turbine generator" mass="50.0" >
		<description>Turbine power generator.</description>
		<maintenance-entity-list>
			<entity name="wind power source" probability="5" max-number="1" />
			<entity name="areothermal power source" probability="5" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="solar panel" mass="10.0" >
		<description>Solar photovoltaic panel.</description>
		<maintenance-entity-list>
			<entity name="solar power source" probability="3" max-number="1" />
			<entity name="electric heat source" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="solar parabolic mirror" mass="50.0" >
		<description>Mirror for solar thermal power source.</description>
		<maintenance-entity-list>
			<entity name="solar thermal power source" probability="3" max-number="1" />
			<entity name="solar heat source" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="glass tube" mass="5.0" >
		<description>Long transparent glass tube.</description>
		<maintenance-entity-list>
			<entity name="solar thermal power source" probability="2" max-number="1" />
<!--
			<entity name="large algae greenhouse" probability="5" max-number="1" />
-->
		</maintenance-entity-list>
	</part>
<!--
	<part name="algae tank" mass="200.0">
		<description>An array of glass tubes connected with pipes and held together by a metal frame.</description>
	</part>
-->
	<part name="brick" mass="2.86">
		<!-- (UK Standard according to Wikipedia) -->
		<description>Construction brick (215mm x 102.5mm x 65mm) 2.86kg</description>
	</part>

	<part name="steel scrap" mass="25.0">
		<description>A 25 kg piece of salvaged steel scrap.</description>
	</part>

	<part name="aluminum scrap" mass="5.0">
		<description>A 5 kg piece of salvaged aluminum scrap.</description>
	</part>

	<part name="bore drill bit" mass="25.0">
		<description>A steel drill bit for drilling bore holes.</description>
	</part>

	<part name="bore drill pipe" mass="50.0">
		<description>A steel pipe for drilling and lining bore holes.</description>
	</part>

	<part name="drilling rig" mass="135.0">
		<description>
			An attachment for light utility vehicle. A motor platform for supporting drilling (used in conjunction with the crane boom)
		</description>
	</part>

	<part name="condenser coil" mass="10.0" >
		<description>Copper tube coil used to condense steam into liquid water.</description>
		<maintenance-entity-list>
			<entity name="areothermal power source" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added an air compressor. -->
	<part name="air compressor" mass="2.0" >
	 	<maintenance-entity-list>
			<entity name="farming" probability="5" max-number="3" />
			<entity name="cooking" probability="5" max-number="3" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added a magnetron tube. 
	<part name="magnetron tube" mass="0.5" >
	</part>
	-->

	<!-- Add power transistor, replacaing the use of heavy, bulky magnetron tube used in microwave oven. 
	see http://www.nxp.com/products/rf/rf-power-transistors/rf-cooking:RF-COOKING?cof=0&am=0   -->
	<part name="power transistor" mass="0.01" >
		<maintenance-entity-list>
		<entity name="farming" probability="1" max-number="2" />
		<entity name="vehicle" probability="1" max-number="2" />
		<entity name="manufacture" probability="1" max-number="2" />
		<entity name="living accommodations" probability="1" max-number="1" />	
		</maintenance-entity-list>
	</part>


	<!-- 2014-11-19 Added a microcontroller. -->
	<part name="microcontroller" mass="0.1" >
		<maintenance-entity-list>
		<entity name="farming" probability="1" max-number="1" />
		<entity name="vehicle" probability="1" max-number="1" />
		<entity name="manufacture" probability="1" max-number="1" />
		<entity name="living accommodations" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added a small transformer. -->
	<part name="small transformer" mass="0.5" >
		<maintenance-entity-list>
		<entity name="farming" probability="3" max-number="1" />
		<entity name="vehicle" probability="3" max-number="1" />
		<entity name="manufacture" probability="3" max-number="2" />
		<entity name="living accommodations" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<!-- 2014-11-19 Added 7 kitchen equipment below -->
	<part name="blender" mass="2.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="oven" mass="10.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="microwave" mass="3.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="ventilation fan" mass="0.2">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
			<entity name="farming" probability="3" max-number="3" />
			<entity name="vehicle" probability="3" max-number="1" />
			<entity name="manufacture" probability="3" max-number="3" />
			<entity name="living accommodations" probability="3" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="stove" mass="20.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="refrigerator" mass="70.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="autoclave" mass="20.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="light emitting diode kit" mass="1.0">
		<maintenance-entity-list>
			<entity name="cooking" probability="3" max-number="5" />
			<entity name="farming" probability="3" max-number="15" />
			<entity name="vehicle" probability="3" max-number="3" />
			<entity name="manufacture" probability="3" max-number="10" />
			<entity name="living accommodations" probability="3" max-number="10" />
			<entity name="life support" probability="5" max-number="4" />
		</maintenance-entity-list>
	</part>

	<part name="light emitting diode bulb" mass="0.1">
		<description>Solid State Light bulb</description>
	</part>

	<part name="high pressure sodium lamp" mass="0.3">
		<description>High Intensity Discharge (HID), and more specifically, High Pressure Sodium (HPS)
			lights have long been used as indoor grow lights, particularly for the late vegetative
			and flowering/fruiting stages of growth.</description>
		<maintenance-entity-list>
			<entity name="farming" probability="3" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="mushroom containment kit" mass="1.0">
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="small semiconductor wafer" mass="1"/>

	<part name="laser sintering 3d printer" mass="50.0">
		<maintenance-entity-list>
			<entity name="manufacture" probability="3" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="carbon dioxide laser" mass="5.0"/>

	<part name="helium neon laser" mass="1.0"/>

	<part name="optical lens" mass=".1" >
			<maintenance-entity-list>
			<entity name="communication" probability="2" max-number="2" />
		</maintenance-entity-list>	
	</part>
	
	<part name="optical prism" mass=".1"/>

	<part name="pathogen filtering system" mass="3.0">
		<maintenance-entity-list>
			<entity name="farming" probability="1" max-number="2" />
			<entity name="dining" probability="2" max-number="2" />
			<entity name="living accommodation" probability="2" max-number="2" />
			<entity name="eva" probability="3" max-number="3" />	
			<entity name="exercise" probability="1" max-number="1" />
			<entity name="waste disposal" probability="3" max-number="2" />
			<entity name="vehicle" probability="1" max-number="1" />
			<entity name="medical care" probability="1" max-number="1" />	 						
		</maintenance-entity-list>
	</part>

	<part name="charcoal filter" mass="1"/>
	
	<part name="electrostatic precipitator" mass=".7"/>

	<part name="large air duct" mass=".3">
		<maintenance-entity-list>
			<entity name="cooking" probability="2" max-number="2" />
			<entity name="farming" probability="2" max-number="2" />
			<entity name="manufacture" probability="2" max-number="2" />
			<entity name="living accommodations" probability="2" max-number="2" />
			<entity name="life support" probability="2" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="flexible hose" mass=".1"/>

	<part name="polycarbonate roofing" mass="1">
		<description>highly transparent, "bullet-resistant" plastic cladding 
			roofing for greenhouses</description>
	</part>

	<part name="small stepper motor" mass="2">
		<description>precision motor for use in 3D printing</description>
		<maintenance-entity-list>
			<entity name="manufacture" probability="1" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="solid oxide fuel cell" mass=".2">
		<description>Each solid oxide fuel cell (SOFC) can generate 200W. 
		It consumes methane and has attained a rating of 65% efficiency</description>
		<!--maintenance-entity-list>
			<entity name="fuel cell stack" probability="1" max-number="25" />
		</maintenance-entity-list-->
	</part>

	<part name="fuel cell stack" mass="15">
		<description>Each fuel cell stack comprises 75 solid oxide fuel cells 
			(SOFC), totalling 15 kWe</description>
	    <maintenance-entity-list>
			<entity name="vehicle" probability="1" max-number="1" />
			<entity name="fuel power source" probability="1" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="portable water purification unit" mass="1">
		<description>The PWPU recycle liquid wastes and is used inside a vehicle/rover </description>
	    <maintenance-entity-list>
			<entity name="vehicle" probability="2" max-number="2" />
		</maintenance-entity-list>
	</part>

	<part name="telescoping antenna" mass="2.0">
		<description>This long transmitting antenna serves to transmit telemetry data for a portable science station in the field. 
		</description>
		<maintenance-entity-list>
			<entity name="vehicle" probability="2" max-number="1" />
			<entity name="communication" probability="2" max-number="1" />
		</maintenance-entity-list>
	</part>

	<part name="gas chromatograph" mass="15.0">
		<description>This portable lab instrument separates the constituents of a volatile substance 
		and is used to gas content analysis. </description>
	</part>

	<part name="mass spectrometer" mass="10.0">
		<description>This portable apparatus can separate isotopes and molecular fragments according to 
		mass. The sample is vaporized and ionized, and the ions are accelerated in an electric 
		field and deflected by a magnetic field into a curved trajectory that 
		gives a distinctive mass spectrum. </description>
	</part>

	<part name="X-ray fluorescene spectrometer" mass="8.0">
		<description>This portable apparatus is used to perform non-destructive chemical analysis of rocks, minerals, sediments and fluids. 
		</description>
	</part>

	<part name="infra-red spectrometer" mass="10.0">
		<description>This portable instrument can identify and study chemicals on a given sample (solid, liquid, or gaseous)
		by using IR spectroscopy to produce an infrared spectrum of the sample. </description>
	</part>

	<part name="heat probe" mass="1.0">
		<description>This instrument is used for thermometry applications in that one can measure temperature inside 
		fluid containers, tanks, and pipes and underground environment</description>
		<maintenance-entity-list>
			<entity name="manufacture" probability="5" max-number="1" />
			<entity name="vehicle" probability="5" max-number="1" />
			<entity name="Living Accommodations" probability="5" max-number="1" />
			<entity name="Life Support" probability="5" max-number="1" />
			<entity name="Farming" probability="5" max-number="1" />
			<entity name="areothermal power source" probability="1" max-number="15" />							
		</maintenance-entity-list>		
	</part>

	<part name="cmos camera" mass="0.5">
		<description>Complementary Metal–Oxide–Semiconductor(CMOS) Camera has an array of CMOS sensors. Each sensor consists
		of millions of pixel sensors, each of which includes a photodetector.</description>
	</part>

	<part name="turbopump" mass="50.0">
		<description>This turbopump is compatible with delivering liquid methane. The purpose of a turbopump is 